apiVersion: v1
kind: ConfigMap
metadata:
  name: config-kong
data:
  KONG_DATABASE: postgres
  KONG_PG_HOST: svc-postgres
  KONG_PG_USER: kong
  KONG_PROXY_ACCESS_LOG: /dev/stderr
  KONG_ADMIN_ERROR_LOG: /dev/stderr
  KONG_LUA_SSL_TRUSTED_CERTIFICATE: system
  KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl