apiVersion: v1
kind: Service
metadata:
  name: svc-kong-proxy
spec:
  type: LoadBalancer
  selector:
    app: kong-proxy
  ports:
  - port: 80
    targetPort: 8000
    name: proxy
  - port: 443
    targetPort: 8443
    name: proxy-ssl
