apiVersion: v1
kind: Service
metadata:
  name: svc-kong-admin
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: kong-proxy
  ports:
  - port: 8001
    targetPort: 8001
    name: admin-api
  - port: 8444
    targetPort: 8444
    name: admin-api-ssl
