apiVersion: batch/v1
kind: Job
metadata:
  name: job-prepare-postgres
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: prepare-postgres
        image: postgres:12.12-alpine
        command:
        - "psql"
        - "-h"
        - "svc-postgres"
        - "-U"
        - "postgres"
        - "-c"
        - "CREATE USER kong WITH PASSWORD 'minhasenhasupersecreta';"
      restartPolicy: Never
