apiVersion: batch/v1
kind: Job
metadata:
  name: job-prepare-admin-api
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: prepare-admin-api
        image: ibmcom/curl:4.0.0
        command:
        - "curl"
        - "-X"
        - "POST"
        - "http://svc-kong-admin:8001/services"
        - "--data"
        - "name=admin-api"
        - "--data"
        - "host=127.0.0.1"
        - "--data"
        - "port=8001"
      restartPolicy: Never
